apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: rust-enterprise-query-engine
      app.kubernetes.io/part-of: rust-enterprise-query-engine
