apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rust-enterprise-query-engine-pvc
  labels:
    app.kubernetes.io/name: rust-enterprise-query-engine
    app.kubernetes.io/part-of: rust-enterprise-query-engine
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
